# Generated by Django 5.1.1 on 2024-09-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usurio',
            name='edad',
            field=models.IntegerField(default=18),
        ),
    ]
